# Generated by Django 4.0.4 on 2022-05-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val_dataset', models.CharField(max_length=100)),
                ('train_dataset', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('num_classes', models.IntegerField(default=5)),
                ('epoch', models.IntegerField(default=300)),
                ('input_channels', models.IntegerField(default=32)),
                ('batch_size', models.IntegerField(default=32)),
                ('lr', models.FloatField(default=0.001)),
                ('weight_decay', models.FloatField(default=0.0001)),
                ('print_freq', models.IntegerField(default=10)),
            ],
        ),
    ]
