# Generated by Django 4.0.4 on 2022-05-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='pre_train',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='train',
            name='start_epoch',
            field=models.IntegerField(default=0),
        ),
    ]
