# Generated by Django 4.0.4 on 2022-05-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0002_train_pre_train_train_start_epoch'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='is_close',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='train',
            name='is_dilate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='train',
            name='is_erode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='train',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
