# Generated by Django 4.0.4 on 2022-05-17 09:45

from django.db import migrations, models
import dl.models


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0003_train_is_close_train_is_dilate_train_is_erode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_model', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to=dl.models.user_directory_path)),
            ],
        ),
    ]
