# Generated by Django 4.0.4 on 2022-05-17 10:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dl', '0004_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 10, 0, 43, 967814, tzinfo=utc)),
        ),
    ]
