# Generated by Django 4.0.4 on 2022-05-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_deep_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='flush_secs',
            field=models.IntegerField(default=30, help_text='tensorboard flush'),
        ),
        migrations.AlterField(
            model_name='train',
            name='model',
            field=models.CharField(help_text='model name', max_length=100),
        ),
    ]
