# Generated by Django 4.0.4 on 2022-05-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_deep_models', '0002_alter_train_flush_secs_alter_train_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='batch',
            field=models.IntegerField(default=32, help_text='batch size', verbose_name='batch_size'),
        ),
        migrations.AlterField(
            model_name='train',
            name='decay_rate',
            field=models.FloatField(default=0, verbose_name='decay_rate'),
        ),
        migrations.AlterField(
            model_name='train',
            name='epoch',
            field=models.IntegerField(default=100, help_text='epoch default 100', verbose_name='epoch'),
        ),
        migrations.AlterField(
            model_name='train',
            name='flush_secs',
            field=models.IntegerField(default=30, help_text='tensorboard flush', verbose_name='flush_secs'),
        ),
        migrations.AlterField(
            model_name='train',
            name='lr',
            field=models.FloatField(default=0.001, help_text='learning rate', verbose_name='lr'),
        ),
        migrations.AlterField(
            model_name='train',
            name='model',
            field=models.CharField(help_text='model name', max_length=100, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='train',
            name='save_prefix',
            field=models.CharField(default='a', help_text='prefix of save name', max_length=10, verbose_name='save_prefix'),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_data',
            field=models.CharField(help_text='train data', max_length=100, verbose_name='train_dataset_path'),
        ),
        migrations.AlterField(
            model_name='train',
            name='val_data',
            field=models.CharField(help_text='validate data', max_length=100, verbose_name='val_dataset_path'),
        ),
    ]
