# Generated by Django 4.0.4 on 2022-05-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_deep_models', '0004_rename_batch_train_batch_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='input_channels',
            field=models.IntegerField(default=32),
        ),
        migrations.AddField(
            model_name='train',
            name='num_classes',
            field=models.IntegerField(default=5),
        ),
    ]
